apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-worker-pod-watcher
  namespace: default
subjects:
  - kind: ServiceAccount
    name: prefect-worker
    namespace: llm-finetuning
roleRef:
  kind: Role
  name: pod-watcher
  apiGroup: rbac.authorization.k8s.io
