apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-run-job
  namespace: llm-finetuning
spec:
  template:
    spec:
      containers:
        - name: prefect-run
          image: localhost:5000/llm-finetuning:latest
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-server.llm-finetuning.svc.cluster.local:4200/api"
          command:
            [
              "prefect",
              "deployment",
              "run",
              "LLM Pipeline/complete-pipeline-deployment",
            ]
      restartPolicy: Never
